// Code generated by goyacc -o lex.go -p brainfuck lex.y. DO NOT EDIT.

//line lex.y:2

package brainfuck

import __yyfmt__ "fmt"

//line lex.y:3

import (
	"fmt"
	"log"
	"unicode/utf8"
)

//line lex.y:13
type brainfuckSymType struct {
	yys  int
	expr Expr
}

var brainfuckToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"'>'",
	"'<'",
	"'+'",
	"'-'",
	"'.'",
	"'['",
	"']'",
}

var brainfuckStatenames = [...]string{}

const brainfuckEofCode = 1
const brainfuckErrCode = 2
const brainfuckInitialStackSize = 16

//line lex.y:40

const eof = 0

type brainfuckLex struct {
	line []byte
	peek rune
}

func (x *brainfuckLex) Lex(lval *brainfuckSymType) int {
	for {
		c := x.next()
		switch c {
		case eof:
			return eof
		case ' ', '\t', '\n', '\r':
		case '<', '>', '+', '-', '.', '[', ']':
			return int(c)
		default:
			log.Printf("unrecognized character %q", c)
		}
	}
}

// Return the next rune for the lexer.
func (x *brainfuckLex) next() rune {
	if x.peek != eof {
		r := x.peek
		x.peek = eof
		return r
	}
	if len(x.line) == 0 {
		return eof
	}
	c, size := utf8.DecodeRune(x.line)
	x.line = x.line[size:]
	if c == utf8.RuneError && size == 1 {
		log.Print("invalid utf8")
		return x.next()
	}
	return c
}

// The parser calls this method on a parse error.
func (x *brainfuckLex) Error(s string) {
	log.Printf("parse error: %s", s)
}

//line yacctab:1
var brainfuckExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const brainfuckPrivate = 57344

const brainfuckLast = 18

var brainfuckAct = [...]int8{
	5, 6, 7, 8, 9, 10, 2, 14, 1, 4,
	11, 12, 3, 0, 0, 0, 0, 13,
}

var brainfuckPact = [...]int16{
	-4, -1000, -1000, -4, -4, -1000, -1000, -1000, -1000, -1000,
	-4, -1000, -1000, -3, -1000,
}

var brainfuckPgo = [...]int8{
	0, 12, 6, 9, 8,
}

var brainfuckR1 = [...]int8{
	0, 4, 2, 2, 2, 2, 3, 1, 1, 1,
	1, 1,
}

var brainfuckR2 = [...]int8{
	0, 1, 2, 1, 2, 1, 3, 1, 1, 1,
	1, 1,
}

var brainfuckChk = [...]int16{
	-1000, -4, -2, -1, -3, 4, 5, 6, 7, 8,
	9, -2, -2, -2, 10,
}

var brainfuckDef = [...]int8{
	0, -2, 1, 3, 5, 7, 8, 9, 10, 11,
	0, 2, 4, 0, 6,
}

var brainfuckTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 6, 3, 7, 8, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	5, 3, 4, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 9, 3, 10,
}

var brainfuckTok2 = [...]int8{
	2, 3,
}

var brainfuckTok3 = [...]int8{
	0,
}

var brainfuckErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	brainfuckDebug        = 0
	brainfuckErrorVerbose = false
)

type brainfuckLexer interface {
	Lex(lval *brainfuckSymType) int
	Error(s string)
}

type brainfuckParser interface {
	Parse(brainfuckLexer) int
	Lookahead() int
}

type brainfuckParserImpl struct {
	lval  brainfuckSymType
	stack [brainfuckInitialStackSize]brainfuckSymType
	char  int
}

func (p *brainfuckParserImpl) Lookahead() int {
	return p.char
}

func brainfuckNewParser() brainfuckParser {
	return &brainfuckParserImpl{}
}

const brainfuckFlag = -1000

func brainfuckTokname(c int) string {
	if c >= 1 && c-1 < len(brainfuckToknames) {
		if brainfuckToknames[c-1] != "" {
			return brainfuckToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func brainfuckStatname(s int) string {
	if s >= 0 && s < len(brainfuckStatenames) {
		if brainfuckStatenames[s] != "" {
			return brainfuckStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func brainfuckErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !brainfuckErrorVerbose {
		return "syntax error"
	}

	for _, e := range brainfuckErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + brainfuckTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(brainfuckPact[state])
	for tok := TOKSTART; tok-1 < len(brainfuckToknames); tok++ {
		if n := base + tok; n >= 0 && n < brainfuckLast && int(brainfuckChk[int(brainfuckAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if brainfuckDef[state] == -2 {
		i := 0
		for brainfuckExca[i] != -1 || int(brainfuckExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; brainfuckExca[i] >= 0; i += 2 {
			tok := int(brainfuckExca[i])
			if tok < TOKSTART || brainfuckExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if brainfuckExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += brainfuckTokname(tok)
	}
	return res
}

func brainfucklex1(lex brainfuckLexer, lval *brainfuckSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(brainfuckTok1[0])
		goto out
	}
	if char < len(brainfuckTok1) {
		token = int(brainfuckTok1[char])
		goto out
	}
	if char >= brainfuckPrivate {
		if char < brainfuckPrivate+len(brainfuckTok2) {
			token = int(brainfuckTok2[char-brainfuckPrivate])
			goto out
		}
	}
	for i := 0; i < len(brainfuckTok3); i += 2 {
		token = int(brainfuckTok3[i+0])
		if token == char {
			token = int(brainfuckTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(brainfuckTok2[1]) /* unknown char */
	}
	if brainfuckDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", brainfuckTokname(token), uint(char))
	}
	return char, token
}

func brainfuckParse(brainfucklex brainfuckLexer) int {
	return brainfuckNewParser().Parse(brainfucklex)
}

func (brainfuckrcvr *brainfuckParserImpl) Parse(brainfucklex brainfuckLexer) int {
	var brainfuckn int
	var brainfuckVAL brainfuckSymType
	var brainfuckDollar []brainfuckSymType
	_ = brainfuckDollar // silence set and not used
	brainfuckS := brainfuckrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	brainfuckstate := 0
	brainfuckrcvr.char = -1
	brainfucktoken := -1 // brainfuckrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		brainfuckstate = -1
		brainfuckrcvr.char = -1
		brainfucktoken = -1
	}()
	brainfuckp := -1
	goto brainfuckstack

ret0:
	return 0

ret1:
	return 1

brainfuckstack:
	/* put a state and value onto the stack */
	if brainfuckDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", brainfuckTokname(brainfucktoken), brainfuckStatname(brainfuckstate))
	}

	brainfuckp++
	if brainfuckp >= len(brainfuckS) {
		nyys := make([]brainfuckSymType, len(brainfuckS)*2)
		copy(nyys, brainfuckS)
		brainfuckS = nyys
	}
	brainfuckS[brainfuckp] = brainfuckVAL
	brainfuckS[brainfuckp].yys = brainfuckstate

brainfucknewstate:
	brainfuckn = int(brainfuckPact[brainfuckstate])
	if brainfuckn <= brainfuckFlag {
		goto brainfuckdefault /* simple state */
	}
	if brainfuckrcvr.char < 0 {
		brainfuckrcvr.char, brainfucktoken = brainfucklex1(brainfucklex, &brainfuckrcvr.lval)
	}
	brainfuckn += brainfucktoken
	if brainfuckn < 0 || brainfuckn >= brainfuckLast {
		goto brainfuckdefault
	}
	brainfuckn = int(brainfuckAct[brainfuckn])
	if int(brainfuckChk[brainfuckn]) == brainfucktoken { /* valid shift */
		brainfuckrcvr.char = -1
		brainfucktoken = -1
		brainfuckVAL = brainfuckrcvr.lval
		brainfuckstate = brainfuckn
		if Errflag > 0 {
			Errflag--
		}
		goto brainfuckstack
	}

brainfuckdefault:
	/* default state action */
	brainfuckn = int(brainfuckDef[brainfuckstate])
	if brainfuckn == -2 {
		if brainfuckrcvr.char < 0 {
			brainfuckrcvr.char, brainfucktoken = brainfucklex1(brainfucklex, &brainfuckrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if brainfuckExca[xi+0] == -1 && int(brainfuckExca[xi+1]) == brainfuckstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			brainfuckn = int(brainfuckExca[xi+0])
			if brainfuckn < 0 || brainfuckn == brainfucktoken {
				break
			}
		}
		brainfuckn = int(brainfuckExca[xi+1])
		if brainfuckn < 0 {
			goto ret0
		}
	}
	if brainfuckn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			brainfucklex.Error(brainfuckErrorMessage(brainfuckstate, brainfucktoken))
			Nerrs++
			if brainfuckDebug >= 1 {
				__yyfmt__.Printf("%s", brainfuckStatname(brainfuckstate))
				__yyfmt__.Printf(" saw %s\n", brainfuckTokname(brainfucktoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for brainfuckp >= 0 {
				brainfuckn = int(brainfuckPact[brainfuckS[brainfuckp].yys]) + brainfuckErrCode
				if brainfuckn >= 0 && brainfuckn < brainfuckLast {
					brainfuckstate = int(brainfuckAct[brainfuckn]) /* simulate a shift of "error" */
					if int(brainfuckChk[brainfuckstate]) == brainfuckErrCode {
						goto brainfuckstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if brainfuckDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", brainfuckS[brainfuckp].yys)
				}
				brainfuckp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if brainfuckDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", brainfuckTokname(brainfucktoken))
			}
			if brainfucktoken == brainfuckEofCode {
				goto ret1
			}
			brainfuckrcvr.char = -1
			brainfucktoken = -1
			goto brainfucknewstate /* try again in the same state */
		}
	}

	/* reduction by production brainfuckn */
	if brainfuckDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", brainfuckn, brainfuckStatname(brainfuckstate))
	}

	brainfucknt := brainfuckn
	brainfuckpt := brainfuckp
	_ = brainfuckpt // guard against "declared and not used"

	brainfuckp -= int(brainfuckR2[brainfuckn])
	// brainfuckp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if brainfuckp+1 >= len(brainfuckS) {
		nyys := make([]brainfuckSymType, len(brainfuckS)*2)
		copy(nyys, brainfuckS)
		brainfuckS = nyys
	}
	brainfuckVAL = brainfuckS[brainfuckp+1]

	/* consult goto table to find next state */
	brainfuckn = int(brainfuckR1[brainfuckn])
	brainfuckg := int(brainfuckPgo[brainfuckn])
	brainfuckj := brainfuckg + brainfuckS[brainfuckp].yys + 1

	if brainfuckj >= brainfuckLast {
		brainfuckstate = int(brainfuckAct[brainfuckg])
	} else {
		brainfuckstate = int(brainfuckAct[brainfuckj])
		if int(brainfuckChk[brainfuckstate]) != -brainfuckn {
			brainfuckstate = int(brainfuckAct[brainfuckg])
		}
	}
	// dummy call; replaced with literal code
	switch brainfucknt {

	case 1:
		brainfuckDollar = brainfuckS[brainfuckpt-1 : brainfuckpt+1]
//line lex.y:22
		{
			NewProgram(3000, brainfuckDollar[1].expr).Run()
			fmt.Println()
		}
	case 2:
		brainfuckDollar = brainfuckS[brainfuckpt-2 : brainfuckpt+1]
//line lex.y:27
		{
			brainfuckVAL.expr = NewList(brainfuckDollar[1].expr, brainfuckDollar[2].expr)
		}
	case 4:
		brainfuckDollar = brainfuckS[brainfuckpt-2 : brainfuckpt+1]
//line lex.y:29
		{
			brainfuckVAL.expr = NewList(brainfuckDollar[1].expr, brainfuckDollar[2].expr)
		}
	case 6:
		brainfuckDollar = brainfuckS[brainfuckpt-3 : brainfuckpt+1]
//line lex.y:32
		{
			brainfuckVAL.expr = NewLoop(brainfuckDollar[2].expr)
		}
	case 7:
		brainfuckDollar = brainfuckS[brainfuckpt-1 : brainfuckpt+1]
//line lex.y:34
		{
			brainfuckVAL.expr = NewIncPtr()
		}
	case 8:
		brainfuckDollar = brainfuckS[brainfuckpt-1 : brainfuckpt+1]
//line lex.y:35
		{
			brainfuckVAL.expr = NewDecPtr()
		}
	case 9:
		brainfuckDollar = brainfuckS[brainfuckpt-1 : brainfuckpt+1]
//line lex.y:36
		{
			brainfuckVAL.expr = NewAdd()
		}
	case 10:
		brainfuckDollar = brainfuckS[brainfuckpt-1 : brainfuckpt+1]
//line lex.y:37
		{
			brainfuckVAL.expr = NewSubtract()
		}
	case 11:
		brainfuckDollar = brainfuckS[brainfuckpt-1 : brainfuckpt+1]
//line lex.y:38
		{
			brainfuckVAL.expr = NewOutput()
		}
	}
	goto brainfuckstack /* stack new state and value */
}
